---
title: "Intro-spatial"
author: "Matthew Hyde"
date: "2023-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("setup.R")
install.packages("tigris")

library(tigris)
rm(list=ls())
counties <- counties(state = "CO")
roads <- roads(state = "CO", county = "Larimer")

install.packages("tmap")
install.packages("htmltools")
library(htmltools)
library(tmap)

tmap_mode("view")

#Using qtm
qtm(counties)+
  qtm(roads)

#Using tm_shape
tm_shape(counties)+
  tm_polygons()+
tm_shape(roads)+
  tm_lines()

unique(roads$RTTYP)
class(counties)


poudre_hwy <- roads %>% 
  filter(FULLNAME == "Poudre Canyon Hwy")

qtm(poudre_hwy)

poudre_points <- data.frame(name = c("Mishawaka", "Rustic", "Blue Lake Trailhead"),
                            long = c(-105.35634, -105.58159, -105.85563),
                            lat = c(40.68752, 40.69687, 40.57960))

library(sf)
poudre_points_sf <- st_as_sf(poudre_points,coords=c("long","lat"),crs = 4326)
qtm(poudre_hwy)+
  qtm(poudre_points_sf)

```

Coordinate Reference systems
```{r}
counties
st_crs(counties)

st_crs(counties) == st_crs(poudre_points_sf)

poudre_points_prj <- st_transform(poudre_points_sf,st_crs(counties))

st_crs(poudre_points_prj) == st_crs(counties)
```
2.2 Raster Data

```{r}
install.packages("elevatr")
library(elevatr)
elevation <- get_elev_raster(counties,z=7)

qtm(elevation)

elevation

install.packages("terra")
library(terra)

elevation <- rast(elevation)
names(elevation) <- "Elevation"

elevation_crop <- crop(elevation, ext(roads))

tm_shape(elevation_crop)+
  tm_raster(style = "cont")

tm_shape(elevation, bbox = st_bbox(poudre_hwy))+
  tm_raster(style = "cont", title = "Elevation (m)")+
tm_shape(poudre_hwy)+
  tm_lines()+
tm_shape(poudre_points_prj)+
  tm_dots(size = 0.2)

write_sf(poudre_hwy, "data/poudre_hwy.shp")

write_sf(poudre_points_prj, "data/poudre_points.shp")
writeRaster(elevation_crop, "data/elevation_larimer.tif")

save(poudre_hwy, poudre_points_prj, file = "data/spatial_objects.RData")
rm(poudre_hwy, poudre_points_prj)
load("data/spatial_objects.RData")

saveRDS(elevation_crop, "data/elevation_crop.RDS")
readRDS("data/elevation_crop.RDS") %>% rast()

rast("data/elevation_larimer.tif")

```

4. Exercises

```{r}

cty_ex <- counties %>%
  select(counties, NAME == "Larimer")

  

```